// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM7fwajm56uqWhsvSH-5D2_e45YEL_-VA',
    appId: '1:808518407186:web:4fa0852150a91805aa74cb',
    messagingSenderId: '808518407186',
    projectId: 'fyp-sharingle-user-app',
    authDomain: 'fyp-sharingle-user-app.firebaseapp.com',
    storageBucket: 'fyp-sharingle-user-app.appspot.com',
    measurementId: 'G-XYXKQNV8LV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hvMlKioW1PsAGVvemI8s3hSW9ZaO1a0',
    appId: '1:808518407186:ios:79416fc4a4f007aaaa74cb',
    messagingSenderId: '808518407186',
    projectId: 'fyp-sharingle-user-app',
    storageBucket: 'fyp-sharingle-user-app.appspot.com',
    iosClientId: '808518407186-qfs9dr5jli7vtoschl2cu8le12js99gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharingleUserApp.RunnerTests',
  );
}
